version: '3.8'

services:
  # 1. PostgreSQL (Dành cho User, Đơn hàng, Thanh toán)
  postgres:
    image: postgres:15-alpine
    container_name: ecommerce_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. MongoDB (Dành cho Sản phẩm, Đánh giá, Audit Log)
  mongo:
    image: mongo:6.0
    container_name: ecommerce_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 3. Redis (Dành cho Giỏ hàng, Cache Trang chủ)
  redis:
    image: redis:7-alpine
    container_name: ecommerce_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # 4. RabbitMQ (Dành cho Worker gửi Email)
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ecommerce_rabbitmq
    restart: always
    ports:
      - "5672:5672"   # Port giao tiếp của message queue
      - "15672:15672" # Port UI Quản trị RabbitMQ
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  mongo_data:
  redis_data:
  rabbitmq_data: